config/routes.rb
Jamesandchristina::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  patch 'rsvp' => "invitations#update", :as => "rsvp"
  get 'rsvp' => "invitations#edit", :as => "invitation"

  get 'rsvp/export' => "invitations#index"

  resources :tables

  root :to => 'welcome#index'

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  has_many :guests, :dependent => :destroy, :inverse_of => :invitation
  accepts_nested_attributes_for :guests, :allow_destroy => true

  before_save :ensure_has_one_guest
  before_create :generate_rsvp
  validates_associated :guests
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_blank => true

  HUMANIZED_ATTRIBUTES = {
    :id => "ID",
    :rsvp => "RSVP",
    :email => "Email address",
    :guests => "Guest(s)"
  }

  scope :attending, -> { where(going: true) }
  scope :not_attending, -> { where(going: false, responded: true) }
  scope :responded, -> { where(responded: true) }
  scope :not_responded, -> { where(going: false, responded: false, invited: true) }

  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  def to_s
    name
  end

  def name
    "#{guests.first}#{guests.length > 1 ? " + #{guests.length - 1}" : ""}"
  end

  def address_name
    families = []
    last_names = {}
    new_last_names = {}
    guests.each do |guest|
      # Discard if name has question marks
      unless guest.name =~ /\?/
        names = guest.name.split(' ')
        # Discard if last name isn't uppercase, it's a placeholder
        if names.last =~ /[A-Z]/
          # If last name ends with a period, it's a suffix
          if names.last =~ /\. *$/
            # Add to last name list for penultimate word
            (last_names[names[-2]] ||= []) << guest.name
          else
            (last_names[names.last] ||= []) << guest.name
          end
        end
      end
    end
    last_names.each do |last_name, names|
      hash_to_use = last_names
      key_to_use = last_name
      if names.length > 1
        first_person_names = names.first.split(' ')
        # If first person has more than two names
        if first_person_names.length > 2
          second_person_names = names[1].split(' ')
          # Check to see if subsequent person has same penultimate name
          if second_person_names.length > 2 && second_person_names[-2] == first_person_names[-2]
            # Create new key for new last name
            hash_to_use = new_last_names
            key_to_use = first_person_names[-2] + ' ' + last_name
            last_names.delete last_name
          end
        end
        hash_to_use[key_to_use] = names.map{|name| name.split(' ').first}
      else
        # Store all words except last name, will be concatenated next
        last_names[last_name] = [names.first.sub(/ [^ ]+ *$/, '')]
      end
    end
    last_names.merge! new_last_names
    last_names.each do |last_name, first_names|
      if last_name == 'Guest'
        families << last_name
      elsif first_names.length > 4 || last_name == 'Rosa'
        families << "The #{last_name} Family"
      else
        families << first_names.to_sentence + ' ' + last_name
      end
    end
    families.to_sentence
  end

  def generate_rsvp
    self.rsvp = ('A'..'Z').to_a.shuffle[0,4].join
  end

  def get_binding
    binding
  end

  private

  def ensure_has_one_guest
    if self.guests.length < 1 || (self.guests.length == 1 && self.guests.first._destroy == true)
      errors.add(:base, 'An invitation must have at least one guest.')
      false
    else
      true
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :find_rsvp, :only => %w{edit update}
  before_action :authenticate_user!, :only => 'index'
  layout false

  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.xml do
        stream = render_to_string(:template=> "invitations/index" )
        send_data(stream, :type=> "text/xml", :filename => "invitations.xml")
      end
      format.xls
    end
  end

  def edit
    @invitation = Invitation.find_by_rsvp(find_rsvp)

    render :edit
  end

  def update
    unless find_rsvp
      raise ActionController::RoutingError.new('Not Found')
    end

    @invitation = Invitation.find_by_rsvp(session[:rsvp]) || Invitation.new

    if @invitation.persisted?
      if params[:invitation] && params[:invitation][:rsvp]
        unless @invitation.responded
          @invitation.going = true
        end
        @invitation.responded = true
        @invitation.save
      else
        if @invitation.update_attributes(params[:invitation].permit(:going, :email, :address, :guests_attributes => [:_destroy, :name, :special_needs, :under_4, :id]))
          flash.now[:notice] = "Thank you for updating your information!"
        else
          flash.now[:alert] = "There was an error saving your information."
        end
      end
      render :edit
    else
      @invitation.errors.add(:base, "We can't find an invitation with that code. Try again!")
      render :partial => "invitations/rsvp"
    end
  end

  private
  def find_rsvp
    if params[:invitation] && params[:invitation][:rsvp]
      session[:rsvp] = params[:invitation][:rsvp].upcase
    elsif session[:rsvp]
      session[:rsvp]
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_guest_fields.html.haml
%fieldset.container
  = f.link_to_remove " Remove this guest".html_safe, :class => "icon-remove-sign"
  -# Moves legend down
  %div
    %legend Guest
  .form_row
    = f.label :name
    = f.text_field :name, :class => 'guest_name'
  .form_row
    = f.label :special_needs
    = f.text_field :special_needs
  -#.form_row
    = f.label :under_4
    = f.check_box :under_4

app/views/invitations/_rsvp.html.haml
.centerer
  %p Enter your RSVP code here:
  = form_for @invitation, :method => 'patch', :url => { :controller => "invitations", :action => "update" } do |f|
    = hidden_field_tag :updating_invitation, true
    = f.text_field :rsvp, :maxlength => 4
    = f.submit "RSVP"
  - if @invitation.errors.present?
    %p= @invitation.errors[:base].first
  - else
    %p
      If you can't make it, please enter your code anyway, and in the next step
      you will be able to set "Attending" to "No" and click "Update Invitation."
    %p
      If you have any issues or would prefer to RSVP another way, please call or
      email us.

app/views/invitations/edit.html.haml
%p
  - if @invitation.going
    Thank you for sending your RSVP!
  - else
    Sorry to miss you at our event.
- if @invitation.going
  %p
    If you can come,
    %strong you're all set.
    If you can't come, or if you need to make any changes, you can do so
    below, then press "Update Invitation".
= nested_form_for @invitation, :method => 'patch', :url => rsvp_path do |f|
  .rsvp__row
    = f.label :going, "Attending"
    = f.radio_button :going, "1", :checked => @invitation.going
    = f.label :going, "Yes", :class => 'rsvp__going'
    = f.radio_button :going, "0", :checked => !@invitation.going
    = f.label :going, "No", :class => 'rsvp__going'
  .rsvp__row
    = f.label :email
    = f.email_field :email
  .rsvp__row
    = f.label :address
    = f.text_area :address, :rows => 4
  = f.fields_for :guests
  = f.link_to_add "Add a guest", :guests
  .rsvp__row.rsvp__row--actions
    = f.submit :class => 'rsvp__button'
    %p.flash
      = flash[:notice]
      = flash[:alert]

app/views/invitations/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Name Line Two</Data></Cell>
        <Cell><Data ss:Type="String">Address Line One</Data></Cell>
        <Cell><Data ss:Type="String">Address Line 2</Data></Cell>
        <Cell><Data ss:Type="String">Address Line 3</Data></Cell>
        <Cell><Data ss:Type="String">Address Line 4</Data></Cell>
        <Cell><Data ss:Type="String">RSVP</Data></Cell>
      </Row>
    <% @invitations.each do |invitation| %>
      <% address_lines = invitation.address.split(/\r?\n/) %>
      <Row>
        <Cell><Data ss:Type="String"><%= invitation.address_name %></Data></Cell>
        <Cell></Cell>
        <Cell><Data ss:Type="String"><%= address_lines[0] || '' %></Data></Cell>
        <Cell><Data ss:Type="String"><%= address_lines[1] || '' %></Data></Cell>
        <Cell><Data ss:Type="String"><%= address_lines[2] || '' %></Data></Cell>
        <Cell><Data ss:Type="String"><%= address_lines[3] || '' %></Data></Cell>
        <Cell><Data ss:Type="String"><%= invitation.rsvp %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/invitations/new.html.haml
%p.intro
  %span.name
    %span.initial<> L
    ily
    = ' '
    %span.initial<> F
    aden
  and
  %br
  %span.name
    %span.initial<> A
    dal
    = ' '
    %span.initial<> H
    ernandez
  %br
  Announce Their Commitment to a
  %br
  %span.name
    %span.initial<> M
    arital
    = ' '
    %span.initial<> U
    nion
  %br
  Ritual, Ceremony and Reception to be held
  %br
  In New York City on
  %br
  %span.date
    %span.initial<> S
    aturday,
    = ' '
    %span.initial<> M
    ay 23, 2015
  %br
  %span.instructions Please submit your address and
  %br
  %span.instructions you will receive a formal invitation by mail
= form_for @invitation do |f|
  .form-row
    = label_tag 'Name(s)'
    = text_field_tag 'name', params[:name], class: 'form-control', required: true
  .form-row
    = f.label :address
    = f.text_area :address, :rows => 4, class: 'form-control', required: true
  .form-row
    = f.label :email
    = f.email_field :email, class: 'form-control'
  .form-row
    = f.label :notes, 'Comments'
    = f.text_area :notes, :rows => 4, class: 'form-control'
  .form-row.form-row--checkbox
    = f.check_box :no_paper_invite
    = f.label :no_paper_invite, 'Opt out of paper invitation'
  .form-row.form-row--submit
    = f.submit 'Submit', class: 'form-submit'
    %p.flash
      = flash[:notice]
      = flash[:alert]

app/views/invitations/thanks.html.haml
.thanks= flash[:notice]