config/routes.rb
Jamesandchristina::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  patch 'rsvp' => "invitations#update", :as => "rsvp"
  get 'rsvp' => "invitations#edit", :as => "invitation"

  get 'rsvp/export' => "invitations#index"

  resources :tables

  root :to => 'welcome#index'

end

app/controllers/tables_controller.rb
require 'rabl'
class TablesController < ApplicationController
  before_action :authenticate_user!

  Rabl.configure do |config|
    config.include_json_root = false
    config.include_child_root = false
  end

  # GET /tables
  # GET /tables.json
  def index
    @title = 'Tables'
    @tables = Table.all

    respond_to do |format|
      format.html {
        @tables_rabl = Rabl.render(@tables, 'tables/index', view_path: 'app/views', format: 'json')
        @guests_rabl = Rabl.render(Guest.attending, 'tables/guests', view_path: 'app/views', format: 'json')
      }
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table].permit(:name, :notes, :x, :y, :table_type, :guest_ids => []))

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render 'tables/create', status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table].permit(:name, :notes, :x, :y, :table_type, :guest_ids => []))
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.haml
- content_for :js do
  :javascript
    var tables = #{@tables_rabl.html_safe}
    var guests = #{@guests_rabl.html_safe}
  = javascript_include_tag 'tables'

#tables
.dance_floor
%section.unassigned_guests
  %h1 Unassigned guests
  %ul#guests.guest_list
%form#new_table
  %h2 New table
  %input{type: 'text', name: 'name', placeholder: 'Name'}
  %select{name: 'table_type'}
    %option{value: 'round'} Round
    %option{value: 'banquet'} Banquet
    %option{value: 'dance_floor'} Dance Floor
  %input{type: 'submit', value: 'Create'}

%script{:type => 'text/template', :id => 'table_template'}
  %h2{contenteditable: true} <%= table.name %>
  <% if (table.table_type !== 'dance_floor') { %>
  %ul.table_guests.guest_list
  <% } %>
  .close_button
    &times;
%script{:type => 'text/template', :id => 'guest_template'}
  <%= name %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>